import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { NATIVE_URL_SCHEME, NATIVE_AUTH_CALLBACK_URL } from '@/lib/platform';

/**
 * The tracked Android and iOS projects are configuration, so they are reviewed
 * like configuration.
 *
 * `android/` and `ios/` are committed rather than regenerated by `cap add` (the
 * decision and its tradeoff are in docs/kiro/NATIVE_RELEASE_GUIDE.md). That
 * choice only pays off if the hardening in them cannot drift: `cap add` would
 * happily overwrite the manifest with a template that declares no backup rules,
 * a wide-open deep link and a debuggable WebView, and nothing in a web test
 * suite would notice.
 *
 * So this suite reads the REAL files that ship, not fixtures, and pins the
 * properties a store review and a privacy review depend on. The Android side has
 * a JVM twin in android/app/src/test/java/app/gomsinlog/NativeConfigTest.java
 * which runs under `./gradlew :app:testDebugUnitTest`; this file is what runs in
 * the plain `npm test` gate, where no Android SDK is required.
 */

const repoRoot = resolve(process.cwd());

function read(relativePath: string): string {
  return readFileSync(join(repoRoot, relativePath), 'utf8');
}

/** Value of a `<key>` in a plist whose value is a `<string>`. */
function plistString(plist: string, key: string): string | null {
  const match = plist.match(
    new RegExp(`<key>${key}</key>\\s*<string>([\\s\\S]*?)</string>`),
  );
  return match ? match[1] : null;
}

/** True when the plist declares `key` at all, whatever its value type. */
function plistHasKey(plist: string, key: string): boolean {
  return new RegExp(`<key>${key}</key>`).test(plist);
}

/**
 * The file with every XML comment removed.
 *
 * These files document what is deliberately ABSENT by naming it, so a negative
 * assertion against the raw text fails on the explanation rather than on a real
 * declaration. Absence has to be checked against the markup only.
 */
function withoutComments(xml: string): string {
  return xml.replace(/<!--[\s\S]*?-->/g, '');
}

/** Every file tracked-or-untracked under `dir`, ignoring build output. */
function walk(dir: string, skip: (path: string) => boolean): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(join(repoRoot, dir))) {
    const relative = `${dir}/${entry}`;
    if (skip(relative)) continue;
    if (statSync(join(repoRoot, relative)).isDirectory()) out.push(...walk(relative, skip));
    else out.push(relative);
  }
  return out;
}

const capacitorConfig = read('capacitor.config.ts');
const manifest = read('android/app/src/main/AndroidManifest.xml');
const appGradle = read('android/app/build.gradle');
const androidSettings = read('android/settings.gradle');
const generatedAndroidSettings = read('android/capacitor.settings.gradle');
const generatedAndroidBuild = read('android/app/capacitor.build.gradle');
const strings = read('android/app/src/main/res/values/strings.xml');
const infoPlist = read('ios/App/App/Info.plist');
const iosPodfile = read('ios/App/Podfile');
const entitlements = read('ios/App/App/App.entitlements');
const privacyManifest = read('ios/App/App/PrivacyInfo.xcprivacy');
const pbxproj = read('ios/App/App.xcodeproj/project.pbxproj');
const packageJson = JSON.parse(read('package.json')) as {
  version: string;
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
};
const devicePluginPackage = JSON.parse(read('packages/capacitor-device-keys/package.json')) as {
  private?: boolean;
  files?: string[];
  capacitor?: { ios?: { src?: string }; android?: { src?: string } };
};
const devicePodspec = read('packages/capacitor-device-keys/GomsinlogCapacitorDeviceKeys.podspec');
const deviceJavaScriptPlugin = read('packages/capacitor-device-keys/src/index.ts');
const deviceAndroidPlugin = read(
  'packages/capacitor-device-keys/android/src/main/java/app/gomsinlog/devicekeys/DeviceKeysPlugin.kt',
);

/** 곰신로그 escaped, so a charset accident cannot make an assertion pass. */
const STORE_LABEL = '\uACF0\uC2E0\uB85C\uADF8';

describe('the deep-link scheme agrees everywhere it is registered', () => {
  it('platform.ts, capacitor.config.ts and both native projects use one literal', () => {
    expect(NATIVE_URL_SCHEME).toBe('gomsinlog');
    expect(capacitorConfig).toContain(`customUrlScheme: '${NATIVE_URL_SCHEME}'`);
    expect(manifest).toContain(`android:scheme="${NATIVE_URL_SCHEME}"`);
    expect(infoPlist).toContain(`<string>${NATIVE_URL_SCHEME}</string>`);
    // The stale Capacitor template value (the appId) is a trap: it looks like a
    // scheme and is what a regenerated manifest would reference.
    expect(strings).toContain(`<string name="custom_url_scheme">${NATIVE_URL_SCHEME}</string>`);
    expect(strings).not.toContain('<string name="custom_url_scheme">app.gomsinlog</string>');
  });

  it('the Android intent-filter pins exactly the callback route the app builds', () => {
    expect(NATIVE_AUTH_CALLBACK_URL).toBe('gomsinlog://auth/callback');
    const filter = manifest.slice(manifest.indexOf('android.intent.action.VIEW'));
    expect(filter).toContain('android:scheme="gomsinlog"');
    expect(filter).toContain('android:host="auth"');
    expect(filter).toContain('android:path="/callback"');
    // A prefix or pattern match would claim every `gomsinlog://` URL again.
    expect(manifest).not.toContain('android:pathPrefix');
    expect(manifest).not.toContain('android:pathPattern');
    expect(manifest).not.toContain('android:pathSuffix');
  });

  it('iOS registers the one scheme and nothing else', () => {
    const urlTypes = infoPlist.slice(
      infoPlist.indexOf('<key>CFBundleURLTypes</key>'),
      infoPlist.indexOf('<key>NSCameraUsageDescription</key>'),
    );
    const schemes = [...urlTypes.matchAll(/<string>([^<]+)<\/string>/g)].map((m) => m[1]);
    expect(schemes).toContain('gomsinlog');
    // Editor / owner role strings are part of the dict; the only *scheme* array
    // entry must be ours, so nothing else may look like a URL scheme.
    expect(schemes.filter((s) => !s.includes('.') && s !== 'Editor' && s !== 'Owner'))
      .toEqual(['gomsinlog']);
    // Universal Links are not used, so no associated domain may appear.
    expect(withoutComments(entitlements)).not.toContain('com.apple.developer.associated-domains');
  });
});

describe('Android: identity, label and store metadata', () => {
  it('uses the immutable applicationId and the Korean store label', () => {
    expect(capacitorConfig).toContain("appId: 'app.gomsinlog'");
    expect(appGradle).toContain('applicationId "app.gomsinlog"');
    expect(strings).toContain(`<string name="app_name">${STORE_LABEL}</string>`);
    expect(strings).toContain(`<string name="title_activity_main">${STORE_LABEL}</string>`);
    expect(manifest).toContain('android:label="@string/app_name"');
  });

  it('keeps versionName equal to package.json so one bump moves both stores', () => {
    expect(appGradle).toContain(`versionName "${packageJson.version}"`);
    expect(appGradle).toMatch(/versionCode \d+/);
  });
});

/**
 * The manifest is heavily commented on purpose -- every permission carries its
 * justification -- and `--` is ILLEGAL inside an XML comment. Adding the
 * ACCESS_NETWORK_STATE rationale above introduced exactly that and would have
 * failed the Android build, which is not runnable in this sandbox (no SDK), so
 * nothing else would have caught it. Cheap guard, real bug.
 */
/**
 * Every OTHER XML the app ships, held to the same rule.
 *
 * The Android guard below was written after a `--` inside a comment broke a
 * manifest. It covered manifests only, so the identical mistake was free to
 * happen in the iOS plist files -- and did, twice in one session, while
 * documenting why an entitlement is deliberately absent. A guard that catches a
 * bug class in one file and not its neighbour is half a guard.
 *
 * `Info.plist` and `App.entitlements` are plists, so a malformed one is not a
 * cosmetic problem: the build embeds the file, and a parse failure there is a
 * failure to declare a usage description or a data-protection class.
 */
describe('the iOS property lists are well-formed XML', () => {
  const IOS_PLISTS = [
    'ios/App/App/Info.plist',
    'ios/App/App/App.entitlements',
    'ios/App/App/PrivacyInfo.xcprivacy',
  ];

  it('covers every plist the app ships (soundness)', () => {
    expect(IOS_PLISTS.length).toBeGreaterThan(0);
    for (const path of IOS_PLISTS) {
      expect(() => read(path), path).not.toThrow();
    }
  });

  it.each(IOS_PLISTS)('%s parses', (path) => {
    const parsed = new DOMParser().parseFromString(read(path), 'application/xml');
    expect(parsed.getElementsByTagName('parsererror')[0]?.textContent ?? null, path).toBeNull();
    expect(parsed.documentElement.tagName, path).toBe('plist');
  });

  it.each(IOS_PLISTS)("%s has no '--' inside a comment", (path) => {
    /*
      The exact rule XML gives comments, and the one people break while writing a
      rationale: `--` may not appear inside `<!-- -->` at all. An em dash reads the
      same and is legal; so does a full stop.
    */
    for (const comment of read(path).match(/<!--[\s\S]*?-->/g) ?? []) {
      expect(comment.slice(4, -3), path).not.toContain('--');
    }
  });
});

describe('the Android manifests are well-formed XML', () => {
  /**
   * Manifests that are COMMITTED, and are therefore the ones a reviewer reads and
   * the ones this branch can actually break. The `--` bug this guard exists for
   * was introduced here, in the ACCESS_NETWORK_STATE rationale.
   */
  const TRACKED_MANIFESTS = ['android/app/src/main/AndroidManifest.xml'];

  /**
   * Manifests `cap sync` GENERATES. They are `.gitignore`-d (android/.gitignore
   * "capacitor-cordova-android-plugins"), so they do not exist in a clean
   * checkout -- which is exactly the state `npm test` runs in, both locally and
   * in CI's web-validation job, where `npm run test` precedes `npx cap sync`.
   *
   * Asserting on them unconditionally made the suite depend on accidental
   * environment state: green on a machine that had run `cap sync`, red on a
   * fresh clone. Their post-sync content is covered by the
   * `capacitor-reproducibility` CI job, which syncs first.
   *
   * They are still checked HERE when present, and their absence is asserted to
   * be the deliberate ignore rule rather than an unexplained gap -- so this
   * block always makes a real assertion and can never silently pass.
   */
  const GENERATED_MANIFESTS = [
    'android/capacitor-cordova-android-plugins/src/main/AndroidManifest.xml',
  ];

  function assertWellFormed(path: string): void {
    const parsed = new DOMParser().parseFromString(read(path), 'application/xml');
    const failure = parsed.getElementsByTagName('parsererror')[0];
    expect(failure?.textContent ?? null, path).toBeNull();
    expect(parsed.documentElement.tagName).toBe('manifest');
  }

  function assertNoDoubleHyphenInComment(path: string): void {
    // Asserted directly as well: some parsers are lenient about it.
    for (const comment of read(path).match(/<!--[\s\S]*?-->/g) ?? []) {
      expect(comment.slice(4, -3), path).not.toContain('--');
    }
  }

  it('the tracked manifest list is not empty (soundness)', () => {
    // Without this, a refactor that emptied the list would make every assertion
    // below vacuous while the suite still reported success.
    expect(TRACKED_MANIFESTS).toContain('android/app/src/main/AndroidManifest.xml');
    for (const path of TRACKED_MANIFESTS) expect(existsSync(join(repoRoot, path)), path).toBe(true);
  });

  for (const path of TRACKED_MANIFESTS) {
    it(`${path} parses`, () => {
      assertWellFormed(path);
    });

    it(`${path} has no '--' inside a comment`, () => {
      assertNoDoubleHyphenInComment(path);
    });
  }

  for (const path of GENERATED_MANIFESTS) {
    it(`${path} is either absent by ignore rule, or well-formed`, () => {
      if (!existsSync(join(repoRoot, path))) {
        // The only acceptable reason to have nothing to check: it is generated
        // and ignored. Both halves are asserted, so a file that went missing for
        // any OTHER reason still fails here.
        expect(read('android/.gitignore')).toContain('capacitor-cordova-android-plugins');
        // ...and the checkout itself is intact, so "absent" really is specific to
        // the generated path rather than a broken cwd or a truncated clone.
        expect(existsSync(join(repoRoot, 'android/app/src/main/AndroidManifest.xml'))).toBe(true);
        return;
      }
      assertWellFormed(path);
      assertNoDoubleHyphenInComment(path);
    });
  }

  it('the guard would catch a double hyphen (soundness)', () => {
    const broken = '<!-- a -- b -->';
    expect(broken.slice(4, -3)).toContain('--');
  });
});

describe('Android: the permission set is exactly what the code proves', () => {
  const declared = [...manifest.matchAll(/<uses-permission android:name="([^"]+)"/g)].map(
    (m) => m[1],
  );

  it('declares INTERNET and ACCESS_NETWORK_STATE, and nothing else', () => {
    // RECORD_AUDIO + MODIFY_AUDIO_SETTINGS left with the voice recorder
    // (§12.4 upload gate, 2026-08-21): no code calls getUserMedia({ audio }),
    // and a microphone permission with no feature behind it is a review flag.
    // They return together when P6 re-admits voice.
    expect([...declared].sort()).toEqual([
      'android.permission.ACCESS_NETWORK_STATE',
      'android.permission.INTERNET',
      // Gate 3. A runtime prompt, asked when a couple connects.
      'android.permission.POST_NOTIFICATIONS',
    ]);
  });

  /**
   * PRIORITY 1, the native half.
   *
   * `navigator.onLine` in an Android WebView is Chromium's network-change
   * notifier, and that notifier can only read connectivity through
   * `ConnectivityManager`, which requires ACCESS_NETWORK_STATE. Undeclared, the
   * query is refused and Chromium reports CONNECTION_NONE -- so `navigator.onLine`
   * is permanently `false` on a perfectly connected device.
   *
   * That flag is not cosmetic here. `useOnlineStatus` TRUSTS `false`, and offline
   * is a PRE-EMPTIVE read-only mode: `TodayLogWidget.handlePost` refuses the write
   * and toasts OFFLINE_READONLY_MESSAGE, 저장 is disabled, and `OfflineBanner`
   * renders "인터넷 연결이 끊겼어요". Reproduced in a real browser as arm D of
   * `scratch/p1-offline.mjs` by forcing the flag: 저장 disabled, zero POSTs, and
   * connection copy on screen -- which is the reported symptom exactly.
   */
  it('declares ACCESS_NETWORK_STATE, without which navigator.onLine is always false', () => {
    expect(declared).toContain('android.permission.ACCESS_NETWORK_STATE');
  });

  it('records why ACCESS_NETWORK_STATE is required, next to the declaration', () => {
    // The manifest's permission block justifies every entry from code in this
    // repo; a connectivity permission with no rationale is how it got missed.
    expect(manifest).toContain('ACCESS_NETWORK_STATE');
    expect(manifest).toContain('navigator.onLine');
    expect(manifest).toContain('useOnlineStatus');
  });

  it('ACCESS_NETWORK_STATE is install-time only, so it needs no runtime rationale', () => {
    // Unlike RECORD_AUDIO it is a normal permission: granted at install, never
    // prompted. So there must be NO in-app prompt copy pretending otherwise.
    expect(read('src/lib/nativePermissions.ts')).not.toContain('ACCESS_NETWORK_STATE');
  });

  it('declares no contacts, location, tracking, advertising or media permission', () => {
    for (const forbidden of [
      'android.permission.CAMERA',
      'android.permission.RECORD_AUDIO',
      'android.permission.MODIFY_AUDIO_SETTINGS',
      'android.permission.ACCESS_FINE_LOCATION',
      'android.permission.ACCESS_COARSE_LOCATION',
      'android.permission.ACCESS_BACKGROUND_LOCATION',
      'android.permission.READ_CONTACTS',
      'android.permission.WRITE_CONTACTS',
      'android.permission.GET_ACCOUNTS',
      'android.permission.READ_PHONE_STATE',
      'android.permission.READ_MEDIA_IMAGES',
      'android.permission.READ_MEDIA_VIDEO',
      'android.permission.READ_MEDIA_AUDIO',
      'android.permission.READ_EXTERNAL_STORAGE',
      'android.permission.WRITE_EXTERNAL_STORAGE',
      'com.google.android.gms.permission.AD_ID',
    ]) {
      expect(declared, forbidden).not.toContain(forbidden);
    }
  });

  it('keeps the microphone rationale parked, not wired: no recorder, no permission, no dangling UI', () => {
    // The rationale module survives for P6 (the copy problem it solves returns
    // unchanged), but nothing in the product may reference it while nothing
    // records -- a microphone explanation without a microphone feature is
    // itself misleading UI.
    const rationale = read('src/lib/nativePermissions.ts');
    expect(rationale).toContain('MICROPHONE_RATIONALE');
    expect(rationale).toContain('PARKED');
    expect(read('src/components/widgets/TodayLogWidget.tsx')).not.toContain('MICROPHONE_RATIONALE');
    expect(read('src/components/widgets/TodayLogWidget.tsx')).not.toContain('getUserMedia');
  });

  it('every component declares android:exported explicitly', () => {
    const components = [
      ...manifest.matchAll(/<(activity|activity-alias|service|receiver|provider)\b[\s\S]*?(?=>)/g),
    ];
    expect(components.length).toBeGreaterThan(0);
    for (const component of components) {
      expect(component[0], component[0].slice(0, 80)).toContain('android:exported=');
    }
  });
});

describe('Android: private records cannot leave through a backup or in the clear', () => {
  it('contains no Capacitor template tests with the old application id', () => {
    expect(existsSync(join(repoRoot, 'android/app/src/test/java/com/getcapacitor/myapp'))).toBe(false);
    expect(existsSync(join(repoRoot, 'android/app/src/androidTest/java/com/getcapacitor/myapp'))).toBe(false);
  });

  it('turns off backup and points both API generations at exclusion rules', () => {
    expect(manifest).toContain('android:allowBackup="false"');
    expect(manifest).toContain('android:fullBackupContent="@xml/backup_rules"');
    expect(manifest).toContain('android:dataExtractionRules="@xml/data_extraction_rules"');
  });

  it('excludes everything from cloud backup AND device transfer', () => {
    const rules = read('android/app/src/main/res/xml/data_extraction_rules.xml');
    for (const section of ['cloud-backup', 'device-transfer']) {
      const body = rules.slice(rules.indexOf(`<${section}>`), rules.indexOf(`</${section}>`));
      expect(body, section).toContain('<exclude domain="root" path="." />');
      expect(body, section).not.toContain('<include');
    }
    expect(read('android/app/src/main/res/xml/backup_rules.xml')).toContain(
      '<exclude domain="root" path="." />',
    );
  });

  it('disables cleartext traffic and does not trust user-installed roots', () => {
    expect(manifest).toContain('android:usesCleartextTraffic="false"');
    expect(manifest).toContain('android:networkSecurityConfig="@xml/network_security_config"');
    const nsc = read('android/app/src/main/res/xml/network_security_config.xml');
    expect(nsc).toContain('cleartextTrafficPermitted="false"');
    expect(nsc).toContain('<certificates src="system" />');
    expect(withoutComments(nsc)).not.toContain('src="user"');
    expect(withoutComments(nsc)).not.toContain('<debug-overrides');
  });

  it('disables WebView remote debugging rather than inheriting it from a build flag', () => {
    expect(capacitorConfig).toMatch(/android:[\s\S]*?webContentsDebuggingEnabled: false/);
    expect(appGradle).toContain('debuggable false');
  });
});

describe('iOS: bundle identity, ATS and usage descriptions', () => {
  it('handles the non-ASCII display name as a real UTF-8 string', () => {
    expect(infoPlist.startsWith('<?xml version="1.0" encoding="UTF-8"?>')).toBe(true);
    expect(plistString(infoPlist, 'CFBundleDisplayName')).toBe(STORE_LABEL);
    // A mojibake'd or entity-escaped label is the usual way this breaks.
    expect(infoPlist).not.toContain('&#');
    expect(plistString(infoPlist, 'CFBundleDevelopmentRegion')).toBe('ko');
    expect(pbxproj).toContain('PRODUCT_BUNDLE_IDENTIFIER = app.gomsinlog;');
  });

  it('keeps MARKETING_VERSION equal to package.json and carries a build number', () => {
    expect(pbxproj).toContain(`MARKETING_VERSION = ${packageJson.version};`);
    expect(pbxproj).toMatch(/CURRENT_PROJECT_VERSION = \d+;/);
    expect(plistString(infoPlist, 'CFBundleShortVersionString')).toBe('$(MARKETING_VERSION)');
    expect(plistString(infoPlist, 'CFBundleVersion')).toBe('$(CURRENT_PROJECT_VERSION)');
  });

  it('leaves App Transport Security at its secure defaults', () => {
    expect(plistHasKey(infoPlist, 'NSAppTransportSecurity')).toBe(false);
    expect(infoPlist).not.toContain('NSAllowsArbitraryLoads');
    expect(infoPlist).not.toContain('NSExceptionAllowsInsecureHTTPLoads');
  });

  it('asks for the camera in Korean and for nothing it does not use', () => {
    // NSMicrophoneUsageDescription left with the voice recorder (§12.4 gate,
    // 2026-08-21): nothing calls getUserMedia({ audio }), so the mic string is
    // now in the not-used list below and returns only with P6 voice.
    const camera = plistString(infoPlist, 'NSCameraUsageDescription');
    expect(camera).toBeTruthy();
    expect(camera!).toMatch(/[\uAC00-\uD7A3]/);
    expect(camera!.length).toBeGreaterThan(20);

    for (const key of [
      'NSMicrophoneUsageDescription',
      'NSPhotoLibraryUsageDescription',
      'NSPhotoLibraryAddUsageDescription',
      'NSUserTrackingUsageDescription',
      'NSLocationWhenInUseUsageDescription',
      'NSLocationAlwaysAndWhenInUseUsageDescription',
      'NSContactsUsageDescription',
      'NSCalendarsUsageDescription',
      'NSSpeechRecognitionUsageDescription',
      'NSFaceIDUsageDescription',
      'NSBluetoothAlwaysUsageDescription',
    ]) {
      expect(plistHasKey(infoPlist, key), key).toBe(false);
    }
  });

  it('ties NSCameraUsageDescription to the capture attribute that requires it', () => {
    // H-2: `capture="environment"` is what makes WKWebView present the camera
    // in-process, and that is the only reason this key exists. If the widget ever
    // drops `capture`, the key must go with it.
    const widget = read('src/components/widgets/TodayLogWidget.tsx');
    const usesCapture = widget.includes("setAttribute('capture', 'environment')");
    expect(plistHasKey(infoPlist, 'NSCameraUsageDescription')).toBe(usesCapture);
    if (usesCapture) {
      expect(plistString(infoPlist, 'NSCameraUsageDescription')!).toMatch(/[\uAC00-\uD7A3]/);
    }
  });

  it('disables the Safari Web Inspector in the shipped configuration', () => {
    expect(capacitorConfig).toMatch(/ios:[\s\S]*?webContentsDebuggingEnabled: false/);
  });
});

describe('iOS: local data is protected and stays out of iCloud and backups', () => {
  it('chooses the file-protection class explicitly instead of inheriting one', () => {
    expect(entitlements).toContain('com.apple.developer.default-data-protection');
    expect(plistString(entitlements, 'com.apple.developer.default-data-protection')).toBe(
      'NSFileProtectionComplete',
    );
    expect(pbxproj).toContain('CODE_SIGN_ENTITLEMENTS = App/App.entitlements;');
  });

  it('excludes the WebKit, cookie and key-value stores from backup at launch', () => {
    const appDelegate = read('ios/App/App/AppDelegate.swift');
    expect(appDelegate).toContain('isExcludedFromBackup = true');
    for (const directory of ['WebKit', 'Cookies', 'HTTPStorages', 'kvstore']) {
      expect(appDelegate, directory).toContain(`"${directory}"`);
    }
    expect(appDelegate).toContain('excludeLocalDataFromBackup()');
    // No iCloud container, so there is nothing else for the data to sync into.
    expect(withoutComments(entitlements)).not.toContain('icloud-container-identifiers');
    expect(withoutComments(entitlements)).not.toContain('ubiquity-container-identifiers');
  });

  it('states the Keychain decision instead of leaving accessibility to a default', () => {
    // The session lives in WKWebView localStorage, not the Keychain, so there is
    // no accessibility class to pick. That is only a safe answer while it stays
    // true, which iosPrivacyManifest.test.ts checks against the real pod sources.
    expect(withoutComments(entitlements)).not.toContain('keychain-access-groups');
    expect(read('docs/kiro/NATIVE_RELEASE_GUIDE.md')).toContain(
      'kSecAttrAccessibleWhenUnlockedThisDeviceOnly',
    );
  });
});

describe('iOS: the privacy manifest ships and is wired into the target', () => {
  it('is a build resource, not an orphan file next to the project', () => {
    expect(pbxproj).toContain('PrivacyInfo.xcprivacy in Resources');
  });

  it('declares no tracking and no tracking domain', () => {
    expect(privacyManifest).toMatch(/<key>NSPrivacyTracking<\/key>\s*<false\/>/);
    expect(privacyManifest).toMatch(/<key>NSPrivacyTrackingDomains<\/key>\s*<array\/>/);
  });

  it('declares the data the app really stores, all for app functionality', () => {
    for (const type of [
      'NSPrivacyCollectedDataTypeEmailAddress',
      'NSPrivacyCollectedDataTypeOtherUserContent',
      'NSPrivacyCollectedDataTypePhotosorVideos',
      'NSPrivacyCollectedDataTypeAudioData',
      'NSPrivacyCollectedDataTypeHealth',
    ]) {
      expect(privacyManifest, type).toContain(type);
    }
    const purposes = [
      ...privacyManifest.matchAll(/<string>NSPrivacyCollectedDataTypePurpose(\w+)<\/string>/g),
    ].map((m) => m[1]);
    expect(purposes.length).toBe(5);
    expect(new Set(purposes)).toEqual(new Set(['AppFunctionality']));
    // Nothing may be marked as used for tracking or advertising.
    expect(privacyManifest).not.toContain('PurposeAdvertising');
    expect(privacyManifest).not.toContain('PurposeAnalytics');
    expect(privacyManifest).not.toMatch(
      /<key>NSPrivacyCollectedDataTypeTracking<\/key>\s*<true\/>/,
    );
  });
});

describe('no signing material is tracked on either platform', () => {
  const skip = (path: string) =>
    /\/(build|Pods|DerivedData|public|\.gradle|capacitor-cordova-(android|ios)-plugins)$/.test(path);
  const nativeFiles = [...walk('android', skip), ...walk('ios', skip)];

  it('the checkout contains no keystore, certificate, profile or store key', () => {
    const forbidden = /\.(jks|keystore|p12|p8|cer|certSigningRequest|mobileprovision|provisionprofile|xcarchive|ipa)$/;
    expect(nativeFiles.filter((f) => forbidden.test(f))).toEqual([]);
    expect(existsSync(join(repoRoot, 'android/keystore.properties'))).toBe(false);
    expect(existsSync(join(repoRoot, 'ios/App/ExportOptions.plist'))).toBe(false);
  });

  it('no build file names a signing config, password or team', () => {
    expect(appGradle).not.toContain('signingConfig');
    expect(appGradle).not.toContain('storePassword');
    expect(appGradle).not.toContain('keyAlias');
    expect(pbxproj).not.toContain('DEVELOPMENT_TEAM');
    expect(pbxproj).not.toContain('PROVISIONING_PROFILE');
  });

  it('.gitignore keeps the whole class out, not just the files that exist today', () => {
    const rootIgnore = read('.gitignore');
    for (const pattern of [
      '*.keystore',
      '*.jks',
      'keystore.properties',
      '*.p12',
      '*.p8',
      '*.cer',
      '*.mobileprovision',
    ]) {
      expect(rootIgnore, pattern).toContain(pattern);
    }
    expect(rootIgnore).toContain('/android/local.properties');
    expect(rootIgnore).toContain('/ios/App/Pods/');
    expect(rootIgnore).toContain('**/xcuserdata/');
    expect(rootIgnore).toContain('/android/build/');
  });

  it('the ignore rules name every generated and machine-local native file', () => {
    for (const generated of [
      'android/local.properties',
      'android/app/src/main/assets/capacitor.config.json',
      'ios/App/App/capacitor.config.json',
      'ios/App/App/config.xml',
    ]) {
      // They may exist on disk after a sync; they must be ignored, which the
      // repository-level check in CI asserts. Here we only require that the
      // ignore rules name them.
      expect(read('.gitignore') + read('android/.gitignore') + read('ios/.gitignore'))
        .toContain(generated.split('/').pop()!);
    }
  });
});

describe('both platforms are installed and reproducible from the lockfile', () => {
  it('@capacitor/ios and @capacitor/android are pinned in devDependencies', () => {
    expect(packageJson.devDependencies['@capacitor/ios']).toBeTruthy();
    expect(packageJson.devDependencies['@capacitor/android']).toBeTruthy();
  });

  it('every pod is a local path reference, so Podfile.lock is a pure function of npm', () => {
    const podfile = read('ios/App/Podfile');
    const pods = [...podfile.matchAll(/pod '([^']+)', :path => '([^']+)'/g)];
    // The count is what keeps the loop below from passing vacuously on a regex
    // that stopped matching. Six since Gate 3 added CapacitorPushNotifications.
    expect(pods.length).toBe(6);
    for (const [, , path] of pods) {
      expect(path.startsWith('../../node_modules/') || path === '../../packages/capacitor-device-keys').toBe(true);
    }
    const lock = read('ios/App/Podfile.lock');
    for (const [, name] of pods) expect(lock, name).toContain(`${name}:`);
  });
});

describe('Capacitor DeviceKeys packaging has one sync-owned native path', () => {
  const LOCAL_PLUGIN = '@gomsinlog/capacitor-device-keys';
  const LOCAL_PATH = 'file:packages/capacitor-device-keys';
  const JS_PLUGIN_NAME = 'GomsinlogDeviceKeys';
  const ANDROID_PROJECT = ':gomsinlog-capacitor-device-keys';
  const IOS_POD = 'GomsinlogCapacitorDeviceKeys';

  it('installs exactly one private local plugin dependency', () => {
    expect(Object.entries(packageJson.dependencies).filter(([name]) => name === LOCAL_PLUGIN))
      .toEqual([[LOCAL_PLUGIN, LOCAL_PATH]]);
    expect(packageJson.devDependencies[LOCAL_PLUGIN]).toBeUndefined();
    expect(devicePluginPackage.private).toBe(true);
  });

  it('removes the obsolete manual Android registration', () => {
    expect(androidSettings).not.toMatch(/:capacitor-device-keys\b/);
    expect(appGradle).not.toMatch(
      /implementation\s+project\s*\(\s*['"]:capacitor-device-keys['"]\s*\)/,
    );
  });

  it('keeps exactly one Capacitor-generated Android project and dependency', () => {
    expect(generatedAndroidSettings).toMatch(
      /include\s+['"]:gomsinlog-capacitor-device-keys['"]/,
    );
    expect(generatedAndroidSettings).toMatch(
      /project\s*\(\s*['"]:gomsinlog-capacitor-device-keys['"]\s*\)\.projectDir\s*=\s*new File\s*\(\s*['"]\.\.\/packages\/capacitor-device-keys\/android['"]\s*\)/,
    );
    expect([...generatedAndroidSettings.matchAll(/include\s+['"]:gomsinlog-capacitor-device-keys['"]/g)])
      .toHaveLength(1);
    expect([...generatedAndroidBuild.matchAll(/implementation\s+project\s*\(\s*['"]:gomsinlog-capacitor-device-keys['"]\s*\)/g)])
      .toHaveLength(1);
    const projectPathReferences = [
      ...`${androidSettings}\n${generatedAndroidSettings}\n${appGradle}\n${generatedAndroidBuild}`
        .matchAll(/projectDir\s*=\s*new File\s*\(\s*['"]\.\.\/packages\/capacitor-device-keys\/android['"]\s*\)/g),
    ];
    expect(projectPathReferences).toHaveLength(1);
  });

  it('preserves the JS/native plugin name at the bridge boundary', () => {
    expect(deviceJavaScriptPlugin).toMatch(
      /registerPlugin<DeviceKeysPlugin>\(\s*['"]GomsinlogDeviceKeys['"]\s*\)/,
    );
    expect(deviceAndroidPlugin).toMatch(
      /@CapacitorPlugin\(\s*name\s*[:=]\s*['"]GomsinlogDeviceKeys['"]\s*\)/,
    );
  });

  it('keeps the iOS Pod target name distinct from the Capacitor plugin name', () => {
    expect(devicePodspec).toMatch(/s\.name\s*=\s*['"]GomsinlogCapacitorDeviceKeys['"]/);
    expect(iosPodfile).toMatch(
      /pod\s+['"]GomsinlogCapacitorDeviceKeys['"]\s*,\s*:path\s*=>/,
    );
    expect(devicePluginPackage.files).toContain('GomsinlogCapacitorDeviceKeys.podspec');
    expect(iosPodfile).not.toMatch(/pod\s+['"]GomsinlogDeviceKeys['"]\s*,/);
    expect(devicePodspec).not.toMatch(/s\.name\s*=\s*['"]GomsinlogDeviceKeys['"]/);
    expect(devicePluginPackage.capacitor).toEqual({ ios: { src: 'ios' }, android: { src: 'android' } });
  });
});
