import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { NATIVE_URL_SCHEME, NATIVE_AUTH_CALLBACK_URL } from '@/lib/platform';

/**
 * The tracked Android and iOS projects are configuration, so they are reviewed
 * like configuration.
 *
 * `android/` and `ios/` are committed rather than regenerated by `cap add` (the
 * decision and its tradeoff are in docs/kiro/NATIVE_RELEASE_GUIDE.md). That
 * choice only pays off if the hardening in them cannot drift: `cap add` would
 * happily overwrite the manifest with a template that declares no backup rules,
 * a wide-open deep link and a debuggable WebView, and nothing in a web test
 * suite would notice.
 *
 * So this suite reads the REAL files that ship, not fixtures, and pins the
 * properties a store review and a privacy review depend on. The Android side has
 * a JVM twin in android/app/src/test/java/app/gomsinlog/NativeConfigTest.java
 * which runs under `./gradlew :app:testDebugUnitTest`; this file is what runs in
 * the plain `npm test` gate, where no Android SDK is required.
 */

const repoRoot = resolve(process.cwd());

function read(relativePath: string): string {
  return readFileSync(join(repoRoot, relativePath), 'utf8');
}

/** Value of a `<key>` in a plist whose value is a `<string>`. */
function plistString(plist: string, key: string): string | null {
  const match = plist.match(
    new RegExp(`<key>${key}</key>\\s*<string>([\\s\\S]*?)</string>`),
  );
  return match ? match[1] : null;
}

/** True when the plist declares `key` at all, whatever its value type. */
function plistHasKey(plist: string, key: string): boolean {
  return new RegExp(`<key>${key}</key>`).test(plist);
}

/**
 * The file with every XML comment removed.
 *
 * These files document what is deliberately ABSENT by naming it, so a negative
 * assertion against the raw text fails on the explanation rather than on a real
 * declaration. Absence has to be checked against the markup only.
 */
function withoutComments(xml: string): string {
  return xml.replace(/<!--[\s\S]*?-->/g, '');
}

/** Every file tracked-or-untracked under `dir`, ignoring build output. */
function walk(dir: string, skip: (path: string) => boolean): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(join(repoRoot, dir))) {
    const relative = `${dir}/${entry}`;
    if (skip(relative)) continue;
    if (statSync(join(repoRoot, relative)).isDirectory()) out.push(...walk(relative, skip));
    else out.push(relative);
  }
  return out;
}

const capacitorConfig = read('capacitor.config.ts');
const manifest = read('android/app/src/main/AndroidManifest.xml');
const appGradle = read('android/app/build.gradle');
const strings = read('android/app/src/main/res/values/strings.xml');
const infoPlist = read('ios/App/App/Info.plist');
const entitlements = read('ios/App/App/App.entitlements');
const privacyManifest = read('ios/App/App/PrivacyInfo.xcprivacy');
const pbxproj = read('ios/App/App.xcodeproj/project.pbxproj');
const packageJson = JSON.parse(read('package.json')) as {
  version: string;
  devDependencies: Record<string, string>;
};

/** 곰신로그 escaped, so a charset accident cannot make an assertion pass. */
const STORE_LABEL = '\uACF0\uC2E0\uB85C\uADF8';

describe('the deep-link scheme agrees everywhere it is registered', () => {
  it('platform.ts, capacitor.config.ts and both native projects use one literal', () => {
    expect(NATIVE_URL_SCHEME).toBe('gomsinlog');
    expect(capacitorConfig).toContain(`customUrlScheme: '${NATIVE_URL_SCHEME}'`);
    expect(manifest).toContain(`android:scheme="${NATIVE_URL_SCHEME}"`);
    expect(infoPlist).toContain(`<string>${NATIVE_URL_SCHEME}</string>`);
    // The stale Capacitor template value (the appId) is a trap: it looks like a
    // scheme and is what a regenerated manifest would reference.
    expect(strings).toContain(`<string name="custom_url_scheme">${NATIVE_URL_SCHEME}</string>`);
    expect(strings).not.toContain('<string name="custom_url_scheme">app.gomsinlog</string>');
  });

  it('the Android intent-filter pins exactly the callback route the app builds', () => {
    expect(NATIVE_AUTH_CALLBACK_URL).toBe('gomsinlog://auth/callback');
    const filter = manifest.slice(manifest.indexOf('android.intent.action.VIEW'));
    expect(filter).toContain('android:scheme="gomsinlog"');
    expect(filter).toContain('android:host="auth"');
    expect(filter).toContain('android:path="/callback"');
    // A prefix or pattern match would claim every `gomsinlog://` URL again.
    expect(manifest).not.toContain('android:pathPrefix');
    expect(manifest).not.toContain('android:pathPattern');
    expect(manifest).not.toContain('android:pathSuffix');
  });

  it('iOS registers the one scheme and nothing else', () => {
    const urlTypes = infoPlist.slice(
      infoPlist.indexOf('<key>CFBundleURLTypes</key>'),
      infoPlist.indexOf('<key>NSMicrophoneUsageDescription</key>'),
    );
    const schemes = [...urlTypes.matchAll(/<string>([^<]+)<\/string>/g)].map((m) => m[1]);
    expect(schemes).toContain('gomsinlog');
    // Editor / owner role strings are part of the dict; the only *scheme* array
    // entry must be ours, so nothing else may look like a URL scheme.
    expect(schemes.filter((s) => !s.includes('.') && s !== 'Editor' && s !== 'Owner'))
      .toEqual(['gomsinlog']);
    // Universal Links are not used, so no associated domain may appear.
    expect(withoutComments(entitlements)).not.toContain('com.apple.developer.associated-domains');
  });
});

describe('Android: identity, label and store metadata', () => {
  it('uses the immutable applicationId and the Korean store label', () => {
    expect(capacitorConfig).toContain("appId: 'app.gomsinlog'");
    expect(appGradle).toContain('applicationId "app.gomsinlog"');
    expect(strings).toContain(`<string name="app_name">${STORE_LABEL}</string>`);
    expect(strings).toContain(`<string name="title_activity_main">${STORE_LABEL}</string>`);
    expect(manifest).toContain('android:label="@string/app_name"');
  });

  it('keeps versionName equal to package.json so one bump moves both stores', () => {
    expect(appGradle).toContain(`versionName "${packageJson.version}"`);
    expect(appGradle).toMatch(/versionCode \d+/);
  });
});

describe('Android: the permission set is exactly what the code proves', () => {
  const declared = [...manifest.matchAll(/<uses-permission android:name="([^"]+)"/g)].map(
    (m) => m[1],
  );

  it('declares INTERNET plus the two the WebView needs for RECORD_AUDIO', () => {
    expect([...declared].sort()).toEqual([
      'android.permission.ACCESS_NETWORK_STATE',
      'android.permission.INTERNET',
      'android.permission.MODIFY_AUDIO_SETTINGS',
      'android.permission.RECORD_AUDIO',
    ]);
  });

  /**
   * PRIORITY 1, the native half.
   *
   * `navigator.onLine` in an Android WebView is Chromium's network-change
   * notifier, and that notifier can only read connectivity through
   * `ConnectivityManager`, which requires ACCESS_NETWORK_STATE. Undeclared, the
   * query is refused and Chromium reports CONNECTION_NONE -- so `navigator.onLine`
   * is permanently `false` on a perfectly connected device.
   *
   * That flag is not cosmetic here. `useOnlineStatus` TRUSTS `false`, and offline
   * is a PRE-EMPTIVE read-only mode: `TodayLogWidget.handlePost` refuses the write
   * and toasts OFFLINE_READONLY_MESSAGE, 저장 is disabled, and `OfflineBanner`
   * renders "인터넷 연결이 끊겼어요". Reproduced in a real browser as arm D of
   * `scratch/p1-offline.mjs` by forcing the flag: 저장 disabled, zero POSTs, and
   * connection copy on screen -- which is the reported symptom exactly.
   */
  it('declares ACCESS_NETWORK_STATE, without which navigator.onLine is always false', () => {
    expect(declared).toContain('android.permission.ACCESS_NETWORK_STATE');
  });

  it('records why ACCESS_NETWORK_STATE is required, next to the declaration', () => {
    // The manifest's permission block justifies every entry from code in this
    // repo; a connectivity permission with no rationale is how it got missed.
    expect(manifest).toContain('ACCESS_NETWORK_STATE');
    expect(manifest).toContain('navigator.onLine');
    expect(manifest).toContain('useOnlineStatus');
  });

  it('ACCESS_NETWORK_STATE is install-time only, so it needs no runtime rationale', () => {
    // Unlike RECORD_AUDIO it is a normal permission: granted at install, never
    // prompted. So there must be NO in-app prompt copy pretending otherwise.
    expect(read('src/lib/nativePermissions.ts')).not.toContain('ACCESS_NETWORK_STATE');
  });

  it('declares no contacts, location, tracking, advertising or media permission', () => {
    for (const forbidden of [
      'android.permission.CAMERA',
      'android.permission.ACCESS_FINE_LOCATION',
      'android.permission.ACCESS_COARSE_LOCATION',
      'android.permission.ACCESS_BACKGROUND_LOCATION',
      'android.permission.READ_CONTACTS',
      'android.permission.WRITE_CONTACTS',
      'android.permission.GET_ACCOUNTS',
      'android.permission.READ_PHONE_STATE',
      'android.permission.READ_MEDIA_IMAGES',
      'android.permission.READ_MEDIA_VIDEO',
      'android.permission.READ_MEDIA_AUDIO',
      'android.permission.READ_EXTERNAL_STORAGE',
      'android.permission.WRITE_EXTERNAL_STORAGE',
      'com.google.android.gms.permission.AD_ID',
    ]) {
      expect(declared, forbidden).not.toContain(forbidden);
    }
  });

  it('RECORD_AUDIO is paired with an in-app Korean rationale, not just a manifest line', () => {
    const rationale = read('src/lib/nativePermissions.ts');
    expect(rationale).toContain('MICROPHONE_RATIONALE');
    expect(rationale).toMatch(/[\uAC00-\uD7A3]/);
    expect(read('src/components/widgets/TodayLogWidget.tsx')).toContain('MICROPHONE_RATIONALE');
  });

  it('every component declares android:exported explicitly', () => {
    const components = [
      ...manifest.matchAll(/<(activity|activity-alias|service|receiver|provider)\b[\s\S]*?(?=>)/g),
    ];
    expect(components.length).toBeGreaterThan(0);
    for (const component of components) {
      expect(component[0], component[0].slice(0, 80)).toContain('android:exported=');
    }
  });
});

describe('Android: private records cannot leave through a backup or in the clear', () => {
  it('turns off backup and points both API generations at exclusion rules', () => {
    expect(manifest).toContain('android:allowBackup="false"');
    expect(manifest).toContain('android:fullBackupContent="@xml/backup_rules"');
    expect(manifest).toContain('android:dataExtractionRules="@xml/data_extraction_rules"');
  });

  it('excludes everything from cloud backup AND device transfer', () => {
    const rules = read('android/app/src/main/res/xml/data_extraction_rules.xml');
    for (const section of ['cloud-backup', 'device-transfer']) {
      const body = rules.slice(rules.indexOf(`<${section}>`), rules.indexOf(`</${section}>`));
      expect(body, section).toContain('<exclude domain="root" path="." />');
      expect(body, section).not.toContain('<include');
    }
    expect(read('android/app/src/main/res/xml/backup_rules.xml')).toContain(
      '<exclude domain="root" path="." />',
    );
  });

  it('disables cleartext traffic and does not trust user-installed roots', () => {
    expect(manifest).toContain('android:usesCleartextTraffic="false"');
    expect(manifest).toContain('android:networkSecurityConfig="@xml/network_security_config"');
    const nsc = read('android/app/src/main/res/xml/network_security_config.xml');
    expect(nsc).toContain('cleartextTrafficPermitted="false"');
    expect(nsc).toContain('<certificates src="system" />');
    expect(withoutComments(nsc)).not.toContain('src="user"');
    expect(withoutComments(nsc)).not.toContain('<debug-overrides');
  });

  it('disables WebView remote debugging rather than inheriting it from a build flag', () => {
    expect(capacitorConfig).toMatch(/android:[\s\S]*?webContentsDebuggingEnabled: false/);
    expect(appGradle).toContain('debuggable false');
  });
});

describe('iOS: bundle identity, ATS and usage descriptions', () => {
  it('handles the non-ASCII display name as a real UTF-8 string', () => {
    expect(infoPlist.startsWith('<?xml version="1.0" encoding="UTF-8"?>')).toBe(true);
    expect(plistString(infoPlist, 'CFBundleDisplayName')).toBe(STORE_LABEL);
    // A mojibake'd or entity-escaped label is the usual way this breaks.
    expect(infoPlist).not.toContain('&#');
    expect(plistString(infoPlist, 'CFBundleDevelopmentRegion')).toBe('ko');
    expect(pbxproj).toContain('PRODUCT_BUNDLE_IDENTIFIER = app.gomsinlog;');
  });

  it('keeps MARKETING_VERSION equal to package.json and carries a build number', () => {
    expect(pbxproj).toContain(`MARKETING_VERSION = ${packageJson.version};`);
    expect(pbxproj).toMatch(/CURRENT_PROJECT_VERSION = \d+;/);
    expect(plistString(infoPlist, 'CFBundleShortVersionString')).toBe('$(MARKETING_VERSION)');
    expect(plistString(infoPlist, 'CFBundleVersion')).toBe('$(CURRENT_PROJECT_VERSION)');
  });

  it('leaves App Transport Security at its secure defaults', () => {
    expect(plistHasKey(infoPlist, 'NSAppTransportSecurity')).toBe(false);
    expect(infoPlist).not.toContain('NSAllowsArbitraryLoads');
    expect(infoPlist).not.toContain('NSExceptionAllowsInsecureHTTPLoads');
  });

  it('asks for the microphone in Korean and for nothing it does not use', () => {
    const microphone = plistString(infoPlist, 'NSMicrophoneUsageDescription');
    expect(microphone).toBeTruthy();
    expect(microphone!).toMatch(/[\uAC00-\uD7A3]/);
    expect(microphone!.length).toBeGreaterThan(20);

    for (const key of [
      'NSPhotoLibraryUsageDescription',
      'NSPhotoLibraryAddUsageDescription',
      'NSUserTrackingUsageDescription',
      'NSLocationWhenInUseUsageDescription',
      'NSLocationAlwaysAndWhenInUseUsageDescription',
      'NSContactsUsageDescription',
      'NSCalendarsUsageDescription',
      'NSSpeechRecognitionUsageDescription',
      'NSFaceIDUsageDescription',
      'NSBluetoothAlwaysUsageDescription',
    ]) {
      expect(plistHasKey(infoPlist, key), key).toBe(false);
    }
  });

  it('ties NSCameraUsageDescription to the capture attribute that requires it', () => {
    // H-2: `capture="environment"` is what makes WKWebView present the camera
    // in-process, and that is the only reason this key exists. If the widget ever
    // drops `capture`, the key must go with it.
    const widget = read('src/components/widgets/TodayLogWidget.tsx');
    const usesCapture = widget.includes("setAttribute('capture', 'environment')");
    expect(plistHasKey(infoPlist, 'NSCameraUsageDescription')).toBe(usesCapture);
    if (usesCapture) {
      expect(plistString(infoPlist, 'NSCameraUsageDescription')!).toMatch(/[\uAC00-\uD7A3]/);
    }
  });

  it('disables the Safari Web Inspector in the shipped configuration', () => {
    expect(capacitorConfig).toMatch(/ios:[\s\S]*?webContentsDebuggingEnabled: false/);
  });
});

describe('iOS: local data is protected and stays out of iCloud and backups', () => {
  it('chooses the file-protection class explicitly instead of inheriting one', () => {
    expect(entitlements).toContain('com.apple.developer.default-data-protection');
    expect(plistString(entitlements, 'com.apple.developer.default-data-protection')).toBe(
      'NSFileProtectionComplete',
    );
    expect(pbxproj).toContain('CODE_SIGN_ENTITLEMENTS = App/App.entitlements;');
  });

  it('excludes the WebKit, cookie and key-value stores from backup at launch', () => {
    const appDelegate = read('ios/App/App/AppDelegate.swift');
    expect(appDelegate).toContain('isExcludedFromBackup = true');
    for (const directory of ['WebKit', 'Cookies', 'HTTPStorages', 'kvstore']) {
      expect(appDelegate, directory).toContain(`"${directory}"`);
    }
    expect(appDelegate).toContain('excludeLocalDataFromBackup()');
    // No iCloud container, so there is nothing else for the data to sync into.
    expect(withoutComments(entitlements)).not.toContain('icloud-container-identifiers');
    expect(withoutComments(entitlements)).not.toContain('ubiquity-container-identifiers');
  });

  it('states the Keychain decision instead of leaving accessibility to a default', () => {
    // The session lives in WKWebView localStorage, not the Keychain, so there is
    // no accessibility class to pick. That is only a safe answer while it stays
    // true, which iosPrivacyManifest.test.ts checks against the real pod sources.
    expect(withoutComments(entitlements)).not.toContain('keychain-access-groups');
    expect(read('docs/kiro/NATIVE_RELEASE_GUIDE.md')).toContain(
      'kSecAttrAccessibleWhenUnlockedThisDeviceOnly',
    );
  });
});

describe('iOS: the privacy manifest ships and is wired into the target', () => {
  it('is a build resource, not an orphan file next to the project', () => {
    expect(pbxproj).toContain('PrivacyInfo.xcprivacy in Resources');
  });

  it('declares no tracking and no tracking domain', () => {
    expect(privacyManifest).toMatch(/<key>NSPrivacyTracking<\/key>\s*<false\/>/);
    expect(privacyManifest).toMatch(/<key>NSPrivacyTrackingDomains<\/key>\s*<array\/>/);
  });

  it('declares the data the app really stores, all for app functionality', () => {
    for (const type of [
      'NSPrivacyCollectedDataTypeEmailAddress',
      'NSPrivacyCollectedDataTypeOtherUserContent',
      'NSPrivacyCollectedDataTypePhotosorVideos',
      'NSPrivacyCollectedDataTypeAudioData',
      'NSPrivacyCollectedDataTypeHealth',
    ]) {
      expect(privacyManifest, type).toContain(type);
    }
    const purposes = [
      ...privacyManifest.matchAll(/<string>NSPrivacyCollectedDataTypePurpose(\w+)<\/string>/g),
    ].map((m) => m[1]);
    expect(purposes.length).toBe(5);
    expect(new Set(purposes)).toEqual(new Set(['AppFunctionality']));
    // Nothing may be marked as used for tracking or advertising.
    expect(privacyManifest).not.toContain('PurposeAdvertising');
    expect(privacyManifest).not.toContain('PurposeAnalytics');
    expect(privacyManifest).not.toMatch(
      /<key>NSPrivacyCollectedDataTypeTracking<\/key>\s*<true\/>/,
    );
  });
});

describe('no signing material is tracked on either platform', () => {
  const skip = (path: string) =>
    /\/(build|Pods|DerivedData|public|\.gradle|capacitor-cordova-(android|ios)-plugins)$/.test(path);
  const nativeFiles = [...walk('android', skip), ...walk('ios', skip)];

  it('the checkout contains no keystore, certificate, profile or store key', () => {
    const forbidden = /\.(jks|keystore|p12|p8|cer|certSigningRequest|mobileprovision|provisionprofile|xcarchive|ipa)$/;
    expect(nativeFiles.filter((f) => forbidden.test(f))).toEqual([]);
    expect(existsSync(join(repoRoot, 'android/keystore.properties'))).toBe(false);
    expect(existsSync(join(repoRoot, 'ios/App/ExportOptions.plist'))).toBe(false);
  });

  it('no build file names a signing config, password or team', () => {
    expect(appGradle).not.toContain('signingConfig');
    expect(appGradle).not.toContain('storePassword');
    expect(appGradle).not.toContain('keyAlias');
    expect(pbxproj).not.toContain('DEVELOPMENT_TEAM');
    expect(pbxproj).not.toContain('PROVISIONING_PROFILE');
  });

  it('.gitignore keeps the whole class out, not just the files that exist today', () => {
    const rootIgnore = read('.gitignore');
    for (const pattern of [
      '*.keystore',
      '*.jks',
      'keystore.properties',
      '*.p12',
      '*.p8',
      '*.cer',
      '*.mobileprovision',
    ]) {
      expect(rootIgnore, pattern).toContain(pattern);
    }
    expect(rootIgnore).toContain('/android/local.properties');
    expect(rootIgnore).toContain('/ios/App/Pods/');
    expect(rootIgnore).toContain('**/xcuserdata/');
    expect(rootIgnore).toContain('/android/build/');
  });

  it('the ignore rules name every generated and machine-local native file', () => {
    for (const generated of [
      'android/local.properties',
      'android/app/src/main/assets/capacitor.config.json',
      'ios/App/App/capacitor.config.json',
      'ios/App/App/config.xml',
    ]) {
      // They may exist on disk after a sync; they must be ignored, which the
      // repository-level check in CI asserts. Here we only require that the
      // ignore rules name them.
      expect(read('.gitignore') + read('android/.gitignore') + read('ios/.gitignore'))
        .toContain(generated.split('/').pop()!);
    }
  });
});

describe('both platforms are installed and reproducible from the lockfile', () => {
  it('@capacitor/ios and @capacitor/android are pinned in devDependencies', () => {
    expect(packageJson.devDependencies['@capacitor/ios']).toBeTruthy();
    expect(packageJson.devDependencies['@capacitor/android']).toBeTruthy();
  });

  it('every pod is a local path reference, so Podfile.lock is a pure function of npm', () => {
    const podfile = read('ios/App/Podfile');
    const pods = [...podfile.matchAll(/pod '([^']+)', :path => '([^']+)'/g)];
    expect(pods.length).toBe(4);
    for (const [, , path] of pods) {
      expect(path.startsWith('../../node_modules/')).toBe(true);
    }
    const lock = read('ios/App/Podfile.lock');
    for (const [, name] of pods) expect(lock, name).toContain(`${name}:`);
  });
});
