/**
 * Partner Briefing Domain and Wire Contract (Phase A1)
 *
 * Defines the minimal pure TypeScript domain contract, model-safe wire payloads,
 * untrusted provider outputs, and verified domain results for GomsinLog Partner Briefing.
 *
 * Architectural invariants:
 * 1. Model-safe events never contain recordId, userId, coupleId, exact date/time,
 *    URLs, storage paths, or key material.
 * 2. Exact record IDs (sourceRecordIds) are bound strictly by TypeScript after
 *    provenance verification, and are never generated by AI.
 * 3. Exact calendar dates exist only in JS/domain final results; native AI
 *    payloads use synthetic dayOrdinal only.
 * 4. Zero external runtime dependencies or legacy DailySummary imports.
 */

export const PARTNER_BRIEFING_VERSION = 1 as const;

/**
 * Provenance classification of the overall briefing output.
 * - 'on_device': Every displayed section is verified model output.
 * - 'hybrid': Verified model sections and deterministic fallback sections coexist.
 * - 'deterministic': No model output is displayed (100% deterministic fallback).
 */
export type BriefingGeneration = 'on_device' | 'hybrid' | 'deterministic';

/**
 * Coarse time-of-day period used across model payloads and domain presentation.
 */
export type BriefingPeriod = 'morning' | 'afternoon' | 'evening' | 'night';

/**
 * Media kinds attached to a source record, stripped of names, paths, and URLs.
 * Compatible with DailyRecord attachment kinds ('photo' | 'video' | 'voice').
 */
export type BriefingMediaKind = 'photo' | 'video' | 'voice';

/**
 * JS-only mapping between a synthetic source ordinal and the actual record ID.
 * Kept strictly on the client side; never sent across the model boundary.
 */
export interface BriefingSourceMapping {
  readonly ordinal: number;
  readonly recordId: string;
}

/**
 * Model-safe event payload sent across the AI boundary.
 *
 * Explicit allowlist: exactly { ordinal, dayOrdinal, period, text, mediaKinds }.
 * Does not extend DailyRecord and contains no user/couple/record IDs,
 * exact timestamps/dates, storage paths, URLs, or cryptographic material.
 */
export interface BriefingModelSafeEvent {
  readonly ordinal: number;
  readonly dayOrdinal: number;
  readonly period: BriefingPeriod;
  readonly text: string;
  readonly mediaKinds: readonly BriefingMediaKind[];
}

/**
 * Untrusted / raw generated section output emitted by an AI model or leaf provider.
 * Contains only text and synthetic source ordinals.
 * Must undergo provenance verification before being bound to real record IDs.
 */
export interface UntrustedBriefingGeneratedSection {
  readonly text: string;
  readonly sourceOrdinals: readonly number[];
}

/**
 * Untrusted / raw response structure from a briefing provider leaf/chunk.
 */
export interface UntrustedBriefingProviderOutput {
  readonly sections: readonly UntrustedBriefingGeneratedSection[];
}

/**
 * Verified briefing overview with bound source record IDs.
 */
export interface PartnerBriefingOverview {
  readonly text: string;
  /**
   * Bound by TypeScript after provenance verification.
   * Never generated by AI.
   */
  readonly sourceRecordIds: readonly string[];
}

/**
 * Verified briefing period section with bound source record IDs.
 */
export interface PartnerBriefingSection {
  readonly period: BriefingPeriod;
  readonly text: string;
  /**
   * Bound by TypeScript after provenance verification.
   * Never generated by AI.
   */
  readonly sourceRecordIds: readonly string[];
}

/**
 * Verified briefing day grouping with bound sections.
 */
export interface PartnerBriefingDay {
  /**
   * Exact ISO date string (e.g. 'YYYY-MM-DD').
   * Managed strictly within JS/domain logic and never exposed to the AI model.
   */
  readonly date: string;
  readonly sections: readonly PartnerBriefingSection[];
}

/**
 * Final verified Partner Briefing domain result.
 */
export interface PartnerBriefing {
  readonly version: 1;
  readonly sourceCount: number;
  readonly generation: BriefingGeneration;
  readonly rangeLabel: string;
  readonly overview: PartnerBriefingOverview;
  readonly days: readonly PartnerBriefingDay[];
}
