-- =============================================================
-- 034_e2ee_recovery_challenge_issuance.sql
-- E2EE Phase 1A: the server-issued recovery challenge.
-- =============================================================
--
-- Additive, and part of the SAME unreleased Phase 1A set as 031 and 032. The
-- rollback file `033_rollback_e2ee_key_foundation.sql.disabled` removes this
-- migration's objects too; it is numbered 033 because it was written before
-- this file existed and is `.disabled`, so it never participates in the forward
-- sequence and its number carries no ordering meaning.
--
-- Forward order is therefore: 031 -> 032 -> 034.
--
-- WHY THIS EXISTS
--
-- `recovery_challenges` was created in 031 with no write path at all: no INSERT
-- policy, no grant, no function. Only `service_role` could write it, by direct
-- table access from an Edge Function. That is a hole in the narrow-RPC
-- discipline every other security-critical write in this schema follows, and it
-- left the client repository calling an `issue-recovery-challenge` function that
-- did not exist.
--
-- Two corrections here:
--
--   1. A challenge is bound to a specific RECOVERY IDENTITY, not merely to a
--      recovery version number. A version is a small integer that repeats
--      across a rotation; the identity is the thing the signature actually
--      chains to. Binding both makes "the identity was replaced" and "the
--      generation was bumped" independently detectable.
--
--   2. Issuance goes through one SECURITY DEFINER function that checks
--      ownership, device state and identity liveness under a row lock, bounds
--      the TTL, and invalidates any earlier unconsumed challenge for the same
--      device. A client can never mint one, which is the property that makes a
--      stolen session plus a full database dump insufficient for recovery.

BEGIN;

-- -------------------------------------------------------------
-- 1. Bind the challenge to a recovery identity
-- -------------------------------------------------------------
-- Challenges are single-use and expire in two minutes, so any row present when
-- this runs is transient by construction. Purging rather than backfilling keeps
-- the column honestly NOT NULL instead of nullable-forever.
DELETE FROM public.recovery_challenges;

ALTER TABLE public.recovery_challenges
  ADD COLUMN IF NOT EXISTS recovery_identity_id UUID;

ALTER TABLE public.recovery_challenges
  ALTER COLUMN recovery_identity_id SET NOT NULL;

-- A challenge is consumed exactly once. `consumed_at` already existed; this
-- index is what makes "one live challenge per device" enforceable rather than
-- merely intended, so a client cannot accumulate a pool of valid challenges and
-- spend them later against a rotated identity.
CREATE UNIQUE INDEX IF NOT EXISTS idx_recovery_challenge_live_device
  ON public.recovery_challenges (new_device_id)
  WHERE consumed_at IS NULL AND new_device_id IS NOT NULL;

COMMENT ON COLUMN public.recovery_challenges.recovery_identity_id IS
  'The recovery identity this challenge authenticates against. Bound so a challenge cannot survive an identity replacement, independently of recovery_version.';

-- -------------------------------------------------------------
-- 2. Issuance
-- -------------------------------------------------------------
-- The challenge BYTES are generated by the Edge Function with WebCrypto and
-- passed in, not by the database. `gen_random_bytes` lives in pgcrypto, whose
-- presence and schema placement vary across Supabase projects; depending on it
-- here would make issuance fail at runtime on a project that never installed
-- it. The Edge Function runs under service_role and is as much "the server" as
-- Postgres is, so the randomness is equally server-controlled either way — and
-- this function still refuses anything a client could influence.
--
-- Returns the row rather than a bare id: the caller needs `issued_at` and
-- `expires_at` exactly as stored, because both are bound into the transcript
-- the recovering device signs. Recomputing them client-side from a local clock
-- would make the signature unverifiable.
CREATE OR REPLACE FUNCTION public.e2ee_issue_recovery_challenge(
  p_user_id UUID,
  p_device_id UUID,
  p_challenge BYTEA,
  p_ttl_seconds INTEGER
)
RETURNS TABLE (
  id UUID,
  user_id UUID,
  recovery_identity_id UUID,
  recovery_version SMALLINT,
  new_device_id UUID,
  challenge_nonce BYTEA,
  issued_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_identity public.recovery_identities;
  v_device public.devices;
  v_id UUID;
BEGIN
  IF p_user_id IS NULL OR p_device_id IS NULL THEN
    RAISE EXCEPTION 'E2EE_CHALLENGE_BAD_REQUEST' USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- 32 bytes, exactly. A shorter challenge is a smaller replay space and there
  -- is no reason to accept one.
  IF p_challenge IS NULL OR octet_length(p_challenge) <> 32 THEN
    RAISE EXCEPTION 'E2EE_CHALLENGE_BAD_NONCE' USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- Bounded TTL. The verifier independently refuses a window wider than its own
  -- limit, so a caller cannot buy itself a long-lived credential here either.
  IF p_ttl_seconds IS NULL OR p_ttl_seconds < 10 OR p_ttl_seconds > 120 THEN
    RAISE EXCEPTION 'E2EE_CHALLENGE_BAD_TTL' USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- The live recovery identity, locked so a concurrent rotation cannot slip
  -- between this read and the insert.
  SELECT * INTO v_identity
  FROM public.recovery_identities
  WHERE recovery_identities.user_id = p_user_id AND superseded_at IS NULL
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'E2EE_NO_RECOVERY_IDENTITY' USING ERRCODE = 'invalid_parameter_value';
  END IF;

  SELECT * INTO v_device FROM public.devices WHERE devices.id = p_device_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'E2EE_UNKNOWN_DEVICE' USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- Ownership, checked here and not merely in the caller.
  IF v_device.user_id IS DISTINCT FROM p_user_id THEN
    RAISE EXCEPTION 'E2EE_DEVICE_WRONG_ACCOUNT' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Only a device that has not yet been anything may start a recovery. An
  -- ACTIVE device does not need one, and a REVOKED device must not get one.
  IF v_device.status <> 'PENDING' THEN
    RAISE EXCEPTION 'E2EE_DEVICE_NOT_PENDING' USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- Supersede any earlier unconsumed challenge for this device. Marking it
  -- consumed rather than deleting keeps the attempt visible to the rate limiter,
  -- which counts issued challenges.
  UPDATE public.recovery_challenges
     SET consumed_at = now()
   WHERE recovery_challenges.new_device_id = p_device_id
     AND recovery_challenges.consumed_at IS NULL;

  INSERT INTO public.recovery_challenges (
    user_id, recovery_identity_id, recovery_version, new_device_id,
    challenge_nonce, issued_at, expires_at
  )
  VALUES (
    p_user_id, v_identity.id, v_identity.recovery_version, p_device_id,
    p_challenge, now(), now() + make_interval(secs => p_ttl_seconds)
  )
  RETURNING recovery_challenges.id INTO v_id;

  RETURN QUERY
  SELECT rc.id, rc.user_id, rc.recovery_identity_id, rc.recovery_version,
         rc.new_device_id, rc.challenge_nonce, rc.issued_at, rc.expires_at
  FROM public.recovery_challenges rc
  WHERE rc.id = v_id;
END;
$$;

COMMENT ON FUNCTION public.e2ee_issue_recovery_challenge(UUID, UUID, BYTEA, INTEGER) IS
  'Server-side recovery challenge issuance. service_role only: a client that could mint a challenge could recover an account from a database dump.';

REVOKE ALL ON FUNCTION public.e2ee_issue_recovery_challenge(UUID, UUID, BYTEA, INTEGER)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.e2ee_issue_recovery_challenge(UUID, UUID, BYTEA, INTEGER)
  TO service_role;

-- -------------------------------------------------------------
-- 3. Consumption, bound to the identity as well as the challenge
-- -------------------------------------------------------------
-- Replaces 031's two-argument version. The signature changes, so the old one is
-- dropped rather than replaced in place; nothing is deployed yet, so there is no
-- compatibility window to preserve.
--
-- The added arguments close a narrow window the two-argument form left open: a
-- challenge issued against identity A could still be consumed after A was
-- superseded by B, because only the Edge Function checked. Now the check
-- happens again inside the same transaction that burns the challenge, under the
-- row lock, where a concurrent rotation cannot interleave.
DROP FUNCTION IF EXISTS public.e2ee_commit_recovery_authentication(UUID, UUID);

CREATE OR REPLACE FUNCTION public.e2ee_commit_recovery_authentication(
  p_challenge_id UUID,
  p_device_id UUID,
  p_recovery_identity_id UUID,
  p_recovery_version SMALLINT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE
  v_rows INTEGER;
  v_challenge public.recovery_challenges;
BEGIN
  SELECT * INTO v_challenge
  FROM public.recovery_challenges
  WHERE id = p_challenge_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'E2EE_UNKNOWN_CHALLENGE' USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- The challenge must still name the identity and generation it was issued
  -- against, and the device it was issued for.
  IF v_challenge.recovery_identity_id IS DISTINCT FROM p_recovery_identity_id
     OR v_challenge.recovery_version IS DISTINCT FROM p_recovery_version THEN
    RAISE EXCEPTION 'E2EE_CHALLENGE_IDENTITY_MISMATCH' USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF v_challenge.new_device_id IS DISTINCT FROM p_device_id THEN
    RAISE EXCEPTION 'E2EE_CHALLENGE_DEVICE_MISMATCH' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- That identity must still be the live one. A superseded generation cannot
  -- authenticate anything, which is the downgrade block.
  IF NOT EXISTS (
    SELECT 1 FROM public.recovery_identities
    WHERE id = p_recovery_identity_id
      AND recovery_version = p_recovery_version
      AND superseded_at IS NULL
  ) THEN
    RAISE EXCEPTION 'E2EE_RECOVERY_IDENTITY_SUPERSEDED' USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- Conditional consumption. Under concurrency exactly one caller updates a
  -- row; every other sees zero and fails, so a challenge can never authenticate
  -- two devices.
  UPDATE public.recovery_challenges
     SET consumed_at = now()
   WHERE id = p_challenge_id
     AND consumed_at IS NULL
     AND expires_at > now();
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  IF v_rows = 0 THEN
    RAISE EXCEPTION 'E2EE_CHALLENGE_ALREADY_USED' USING ERRCODE = 'unique_violation';
  END IF;

  -- Authenticated is NOT provisioned: the device is still not an eligible
  -- envelope recipient and still has no certificate.
  UPDATE public.devices
     SET status = 'RECOVERY_AUTHENTICATED', enrollment_method = 'recovery'
   WHERE id = p_device_id AND status = 'PENDING';
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  IF v_rows = 0 THEN
    -- Same transaction, so the challenge is NOT burned by this failure.
    RAISE EXCEPTION 'E2EE_DEVICE_NOT_PENDING' USING ERRCODE = 'invalid_parameter_value';
  END IF;

  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.e2ee_commit_recovery_authentication(UUID, UUID, UUID, SMALLINT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.e2ee_commit_recovery_authentication(UUID, UUID, UUID, SMALLINT)
  TO service_role;

-- -------------------------------------------------------------
-- 4. PostgREST schema cache
-- -------------------------------------------------------------
-- New and changed function signatures; without this the cache keeps the old
-- list and callers get PGRST202 until someone reloads by hand.
NOTIFY pgrst, 'reload schema';

COMMIT;
