require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  pod 'GomsinlogCapacitorAppleAuth', :path => '../../packages/capacitor-apple-auth'
  pod 'GomsinlogCapacitorDeviceKeys', :path => '../../packages/capacitor-device-keys'
  pod 'GomsinlogCapacitorOnDeviceBriefing', :path => '../../packages/capacitor-on-device-briefing'
  pod 'GomsinlogCapacitorOnDeviceSummary', :path => '../../packages/capacitor-on-device-summary'
  pod 'GomsinlogCapacitorStorekit', :path => '../../packages/capacitor-storekit'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
